// Muscle groups with their corresponding 3D models
export const MUSCLE_GROUPS = {
  chest: {
    name: 'Chest',
    color: '#ff4444',
    position: [-0.03, 0.56, 0.12],
    scale: [0.19, 0.08, 0.07],
    rotation: [0, 0, 0],
    opacity: 0.5,
    modelPath: '/3D/Chest.glb',
    description: 'Major upper-body muscle involved in pushing movements.',
    primaryFunctions: ['Horizontal adduction of the arm', 'Shoulder flexion', 'Stabilization during press movements'],
    workouts: [
      {
        name: 'Barbell Bench Press',
        type: 'Compound', 
        equipment: 'Barbell, bench',
        cues: 'Keep shoulder blades pinched, drive through chest, full range of motion.',
        sampleSetsReps: '4 sets x 6–8 reps',
      },
      {
        name: 'Incline Dumbbell Press',
        type: 'Compound',
        equipment: 'Dumbbells, incline bench',
        cues: 'Slight arch in lower back, press diagonally upward, control descent.',
        sampleSetsReps: '3 sets x 8–12 reps',
      },
      {
        name: 'Cable Fly',
        type: 'Isolation',
        equipment: 'Cable machine',
        cues: 'Elbows slightly bent, squeeze at peak, slow return.',
        sampleSetsReps: '3 sets x 12–15 reps',
      },
    ],
  },
  biceps_left: {
    name: 'Left Bicep',
    color: '#44ff44',
    position: [0.32, 0.48, 0.04],
    scale: [0.08, 0.05, 0.03],
    rotation: [0, 0, 0],
    opacity: 0.5,
    modelPath: '/3D/Arm.glb',
    description: 'Anterior upper-arm muscle responsible for elbow flexion and forearm supination.',
    primaryFunctions: ['Elbow flexion', 'Forearm supination'],
    workouts: [
      {
        name: 'Standing Dumbbell Curl',
        type: 'Isolation',
        equipment: 'Dumbbells',
        cues: 'Keep elbows fixed at sides, avoid swinging, squeeze at top.',
        sampleSetsReps: '3 sets x 10–12 reps',
      },
      {
        name: 'Hammer Curl',
        type: 'Isolation',
        equipment: 'Dumbbells',
        cues: 'Neutral grip, control both concentric and eccentric phases.',
        sampleSetsReps: '3 sets x 10 reps',
      },
    ],
  },
  biceps_right: {
    name: 'Right Bicep',
    color: '#44ff44',
    position: [-0.32, 0.48, 0.04],
    scale: [0.08, 0.05, 0.03],
    rotation: [0, 0, 0],
    opacity: 0.6,
    modelPath: '/3D/Arm.glb',
    description: 'Anterior upper-arm muscle responsible for elbow flexion and forearm supination.',
    primaryFunctions: ['Elbow flexion', 'Forearm supination'],
    workouts: [
      {
        name: 'EZ-Bar Curl',
        type: 'Isolation',
        equipment: 'EZ bar',
        cues: 'Grip width comfortable, avoid swinging, full contraction.',
        sampleSetsReps: '4 sets x 8–10 reps',
      },
      {
        name: 'Concentration Curl',
        type: 'Isolation',
        equipment: 'Dumbbell',
        cues: 'Slow controlled reps, focus on peak squeeze.',
        sampleSetsReps: '3 sets x 12 reps',
      },
    ],
  },
  shoulders_left: {
    name: 'Left Shoulder',
    color: '#4444ff',
    position: [0.28, 0.59, -0.06],
    scale: [0.05, 0.05, 0.05],
    rotation: [0, 0, 0],
    opacity: 0.6,
    modelPath: '/3D/Upperarm.glb',
    description: 'Deltoid complex responsible for arm abduction and stabilization.',
    primaryFunctions: ['Arm abduction', 'Shoulder flexion/extension', 'Rotation'],
    workouts: [
      {
        name: 'Seated Dumbbell Press',
        type: 'Compound',
        equipment: 'Dumbbells, bench',
        cues: 'Keep back neutral, press overhead without flaring elbows too wide.',
        sampleSetsReps: '4 sets x 8 reps',
      },
      {
        name: 'Lateral Raise',
        type: 'Isolation',
        equipment: 'Dumbbells',
        cues: 'Slight bend in elbow, raise to shoulder height, avoid momentum.',
        sampleSetsReps: '3 sets x 12–15 reps',
      },
    ],
  },
  shoulders_right: {
    name: 'Right Shoulder',
    color: '#4444ff',
    position: [-0.28, 0.59, -0.06],
    scale: [0.05, 0.05, 0.05],
    rotation: [0, 0, 0],
    opacity: 0.6,
    modelPath: '/3D/Upperarm.glb',
    description: 'Deltoid complex responsible for arm abduction and stabilization.',
    primaryFunctions: ['Arm abduction', 'Shoulder flexion/extension', 'Rotation'],
    workouts: [
      {
        name: 'Arnold Press',
        type: 'Compound',
        equipment: 'Dumbbells',
        cues: 'Rotate wrists during press for full deltoid engagement.',
        sampleSetsReps: '3 sets x 10 reps',
      },
      {
        name: 'Front Raise',
        type: 'Isolation',
        equipment: 'Plate or dumbbell',
        cues: 'Lift with shoulders, not momentum; pause at top.',
        sampleSetsReps: '3 sets x 12 reps',
      },
    ],
  },
  abs: {
    name: 'Abs',
    color: '#ffff44',
    position: [-0.01, 0.29, 0.18],
    scale: [0.11, 0.18, 0.04],
    rotation: [0, 0, 0],
    opacity: 0.6,
    modelPath: '/3D/Abs.glb',
    description: 'Core muscles that stabilize the trunk and assist in flexion.',
    primaryFunctions: ['Spinal flexion', 'Core stabilization', 'Intra-abdominal pressure control'],
    workouts: [
      {
        name: 'Hanging Leg Raise',
        type: 'Core',
        equipment: 'Pull-up bar',
        cues: 'Avoid swinging, lead with hips, control descent.',
        sampleSetsReps: '3 sets x 10–15 reps',
      },
      {
        name: 'Plank',
        type: 'Isometric',
        equipment: 'Bodyweight',
        cues: 'Neutral spine, squeeze glutes and abs, breathe steadily.',
        sampleSetsReps: '3 x 45–60 seconds',
      },
    ],
  },
  back: {
    name: 'Back',
    color: '#ffb144',
    position: [0.00, 0.46, -0.15],
    scale: [0.15, 0.24, 0.04],
    rotation: [0, 0, 0],
    opacity: 0.6,
    modelPath: '/3D/Back.glb',
    description: 'Posterior chain component involved in pulling and posture support.',
    primaryFunctions: ['Spinal extension', 'Scapular retraction', 'Arm adduction'],
    workouts: [
      {
        name: 'Bent-over Barbell Row',
        type: 'Compound',
        equipment: 'Barbell',
        cues: 'Hinge at hips, pull to lower ribs, keep torso stable.',
        sampleSetsReps: '4 sets x 6–8 reps',
      },
      {
        name: 'Pull-up / Chin-up',
        type: 'Bodyweight',
        equipment: 'Pull-up bar',
        cues: 'Full range, avoid kipping (unless intended), squeeze back at top.',
        sampleSetsReps: '3 sets to failure or 6–10 reps weighted',
      },
    ],
  },
  quads_left: {
    name: 'Left Quadriceps',
    color: '#ff44ff',
    position: [0.15, -0.15, 0.15],
    scale: [0.08, 0.23, 0.05],
    rotation: [0, 0, 0],
    opacity: 0.6,
    modelPath: '/3D/Upperleg.glb',
    description: 'Front thigh muscles responsible for knee extension and hip flexion.',
    primaryFunctions: ['Knee extension', 'Hip flexion (rectus femoris)'],
    workouts: [
      {
        name: 'Back Squat',
        type: 'Compound',
        equipment: 'Barbell',
        cues: 'Drive through heels, knees tracking toes, full depth as mobility allows.',
        sampleSetsReps: '5 sets x 5 reps',
      },
      {
        name: 'Leg Extension',
        type: 'Isolation',
        equipment: 'Machine',
        cues: 'Controlled squeeze at top, avoid locking out violently.',
        sampleSetsReps: '3 sets x 12–15 reps',
      },
    ],
  },
  quads_right: {
    name: 'Right Quadriceps',
    color: '#ff44ff',
    position: [-0.15, -0.15, 0.15],
    scale: [0.08, 0.23, 0.05],
    rotation: [0, 0, 0],
    opacity: 0.6,
    modelPath: '/3D/Upperleg.glb',
    description: 'Front thigh muscles responsible for knee extension and hip flexion.',
    primaryFunctions: ['Knee extension', 'Hip flexion (rectus femoris)'],
    workouts: [
      {
        name: 'Front Squat',
        type: 'Compound',
        equipment: 'Barbell',
        cues: 'Upright torso, elbow high, drive through mid-foot.',
        sampleSetsReps: '4 sets x 6–8 reps',
      },
      {
        name: 'Walking Lunges',
        type: 'Compound',
        equipment: 'Bodyweight or dumbbells',
        cues: 'Long stride, knee tracking, core tight.',
        sampleSetsReps: '3 sets x 10 steps per leg',
      },
    ],
  },
  calves_left: {
    name: 'Left Calf',
    color: '#44ffff',
    position: [0.18, -0.57, -0.18],
    scale: [0.06, 0.15, 0.04],
    rotation: [0, 0, 0],
    opacity: 0.6,
    modelPath: '/3D/Calves.glb',
    description: 'Lower leg muscles responsible for plantarflexion of the foot.',
    primaryFunctions: ['Plantarflexion', 'Ankle stabilization'],
    workouts: [
      {
        name: 'Standing Calf Raise',
        type: 'Isolation',
        equipment: 'Machine or bodyweight',
        cues: 'Full stretch and contraction, pause at top.',
        sampleSetsReps: '4 sets x 15–20 reps',
      },
    ],
  },
  calves_right: {
    name: 'Right Calf',
    color: '#44ffff',
    position: [-0.18, -0.57, -0.18],
    scale: [0.06, 0.15, 0.04],
    rotation: [0, 0, 0],
    opacity: 0.6,
    modelPath: '/3D/Calves.glb',
    description: 'Lower leg muscles responsible for plantarflexion of the foot.',
    primaryFunctions: ['Plantarflexion', 'Ankle stabilization'],
    workouts: [
      {
        name: 'Seated Calf Raise',
        type: 'Isolation',
        equipment: 'Machine',
        cues: 'Focus on soleus engagement, slow negative.',
        sampleSetsReps: '3 sets x 20 reps',
      },
    ],
  },
  forearm_right: {
    name: 'Right Forearm',
    color: '#44ffff',
    position: [-0.48, 0.26, 0.04],
    scale: [0.11, 0.07, 0.07],
    rotation: [0, 0, 0],
    opacity: 0.6,
    modelPath: '/3D/Forearm.glb',
    description: 'Muscles involved in wrist flexion/extension and grip strength.',
    primaryFunctions: ['Wrist movement', 'Grip stabilization'],
    workouts: [
      {
        name: 'Wrist Curl',
        type: 'Isolation',
        equipment: 'Dumbbell or barbell',
        cues: 'Slow controlled reps, full range.',
        sampleSetsReps: '3 sets x 15 reps',
      },
      {
        name: 'Farmer\'s Carry',
        type: 'Grip/Compound',
        equipment: 'Heavy dumbbells or kettlebells',
        cues: 'Neutral spine, steady walk, strong grip.',
        sampleSetsReps: '3 x 30 seconds walks',
      },
    ],
  },
  forearm_left: {
    name: 'Left Forearm',
    color: '#44ffff',
    position: [0.48, 0.26, 0.04],
    scale: [0.11, 0.07, 0.07],
    rotation: [0, 0, 0],
    opacity: 0.6,
    modelPath: '/3D/Forearm.glb',
    description: 'Muscles involved in wrist flexion/extension and grip strength.',
    primaryFunctions: ['Wrist movement', 'Grip stabilization'],
    workouts: [
      {
        name: 'Reverse Curl',
        type: 'Isolation',
        equipment: 'EZ bar or dumbbell',
        cues: 'Pronated grip, control eccentric portion.',
        sampleSetsReps: '3 sets x 12 reps',
      },
    ],
  },
};
